name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: Local Model (llama-server)
    provider: openai
    apiBase: http://localhost:11434/v1
    apiKey: none
    model: AUTODETECT
    roles:
      - chat
      - edit
      - apply
